# This is a basic workflow to help you get started with Actions

name: Dev CI/CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs
  #build the app
  buildBeforeTest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checks-out Repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: '14.x'

      # install applicaion dependencies and build
      - name: Install Dependencies & build angular
        run: |
          npm install
          npm install -g @angular/cli 
          npm run build
